// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiApi.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20260316125426_AgregadosPaisesAhoraDeVerdadEspero")]
    partial class AgregadosPaisesAhoraDeVerdadEspero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("biblioteca")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Property<int>("Empresa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Empresa_Id"));

                    b.Property<DateTime>("Empresa_Fecha_Creacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("empresa_fecha_creacion");

                    b.Property<string>("Empresa_Logo")
                        .HasColumnType("text")
                        .HasColumnName("empresa_logo");

                    b.Property<string>("Empresa_Nombre")
                        .HasColumnType("text")
                        .HasColumnName("empresa_nombre");

                    b.Property<int?>("Empresa_PaisPais_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Empresa_Pais_Origen")
                        .HasColumnType("text")
                        .HasColumnName("empresa_pais_origen");

                    b.HasKey("Empresa_Id");

                    b.HasIndex("Empresa_PaisPais_Id");

                    b.ToTable("empresa", "biblioteca");
                });

            modelBuilder.Entity("Pais", b =>
                {
                    b.Property<int>("Pais_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pais_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pais_Id"));

                    b.Property<int>("Pais_Habitantes")
                        .HasColumnType("integer")
                        .HasColumnName("pais_habitantes");

                    b.Property<string>("Pais_Nombre")
                        .HasColumnType("text")
                        .HasColumnName("pais_nombre");

                    b.HasKey("Pais_Id");

                    b.ToTable("pais", "biblioteca");
                });

            modelBuilder.Entity("Empresa", b =>
                {
                    b.HasOne("Pais", "Empresa_Pais")
                        .WithMany("Pais_Empresas")
                        .HasForeignKey("Empresa_PaisPais_Id");

                    b.Navigation("Empresa_Pais");
                });

            modelBuilder.Entity("Pais", b =>
                {
                    b.Navigation("Pais_Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
