// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiApi.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20260316094355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("biblioteca")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Property<int>("Empresa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Empresa_Id"));

                    b.Property<DateTime>("Empresa_Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Empresa_Logo")
                        .HasColumnType("text");

                    b.Property<string>("Empresa_Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Empresa_Pais_Origen")
                        .HasColumnType("text");

                    b.HasKey("Empresa_Id");

                    b.ToTable("empresa", "biblioteca");
                });
#pragma warning restore 612, 618
        }
    }
}
