// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiApi.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Property<int>("Empresa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Empresa_Id"));

                    b.Property<DateTime>("Empresa_Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Empresa_Logo")
                        .HasColumnType("text");

                    b.Property<string>("Empresa_Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Empresa_Pais_Origen")
                        .HasColumnType("text");

                    b.Property<int>("Pais_Id")
                        .HasColumnType("integer");

                    b.HasKey("Empresa_Id");

                    b.HasIndex("Pais_Id");

                    b.ToTable("empresa", "public");
                });

            modelBuilder.Entity("Pais", b =>
                {
                    b.Property<int>("Pais_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pais_Id"));

                    b.Property<int>("Pais_Habitantes")
                        .HasColumnType("integer");

                    b.Property<string>("Pais_Nombre")
                        .HasColumnType("text");

                    b.HasKey("Pais_Id");

                    b.ToTable("pais", "public");
                });

            modelBuilder.Entity("Empresa", b =>
                {
                    b.HasOne("Pais", "Empresa_Pais")
                        .WithMany("Pais_Empresas")
                        .HasForeignKey("Pais_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa_Pais");
                });

            modelBuilder.Entity("Pais", b =>
                {
                    b.Navigation("Pais_Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
